### ISSUE TITLE
Change naming scheme for identifiers

### ISSUE THREAD

**Issue by AndrewAnnex** [AndrewAnnex/planetcantile#19]
This will be semi controversial, but I am considering the possibility of changing the naming scheme to avoid direct use of the IAU CRS codes which aren't well known. Other TMS specs tend to use words like 'WorldCRS84Quad' or 'UPSAntarcticWGS84Quad' rather than the exact epsg code. The issue being that currently we don't have a way to make multiple tms specs for the same CRS with different properties like different numbers of zoom levels.

This may just not matter that much, but it could make sense to rename the codes to use shortened versions of the IAU CRS titles, so 49930 could be something like 'MarsSphereNPStereographic' for a quick but not final example schema

**Comment by jlaura** [comment]
My initial impression is that this makes a lot of sense. IAU_2015:30100 either means everything to the reader or nothing at all. For the vast majority of readers, it means nothing (which is fine). Anything that can be done to lower the bar for usage is a step in the right direction from my perspective.
